language: python
python:
  - 2.7
install:
  - pip install .
script: nosetests
deploy:
  provider: releases
  api_key: $TOKEN
  on:
    branch: master
    condition: "`git log -1 --pretty=%B` == $\"Hammr release\"*"